version: "3"

services:

  filmcoin-nginx:
    image: nginx:stable-alpine
    container_name: filmcoin-nginx
    restart: always
    expose:
      - 80
    volumes:
      - ./public/:/usr/share/nginx/html/
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
    environment:
      VIRTUAL_HOST: thefilmcoin.io
      LETSENCRYPT_HOST: thefilmcoin.io
      LETSENCRYPT_EMAIL: luisrosero@useit.co